In [ ]:
import pandas as pd

# Read the CSV file
df = pd.read_csv('BTC-2019min.csv')

# Convert the 'Date' column to datetime format
df['date'] = pd.to_datetime(df['date'])

# Filter the data between 4 March 2019 and 10 December 2019
start_date = pd.to_datetime('2019-03-04')
end_date = pd.to_datetime('2019-12-18')
filtered_data = df.loc[(df['date'] >= start_date) & (df['date'] <= end_date)]


filtered_data = filtered_data[['date','open','high','low','close']]

#inverse the rows,to have increasing date
filtered_data = filtered_data.iloc[::-1]

#drop the last row
filtered_data = filtered_data.drop(filtered_data.index[-1])


# Save the filtered data to a new CSV file
filtered_data.to_csv('bitcoin_minuntely.csv', index=False)

bitcoin = filtered_data

In [ ]:
import pandas as pd
import numpy as np

bitcoin = pd.read_csv('bitcoin_minuntely.csv')

bitcoin = bitcoin[['date','high']]

num_rows = bitcoin.shape[0]

end_day = pd.to_datetime('2019-12-11')

m = [1, 5, 15, 60 , 10080]
returns_mean = []
allreturns = []

for horizon in m:

  returns = list()

  i = 0

  while(pd.to_datetime(bitcoin['date'].iloc[ i ]) < end_day ):

    returns.append( (bitcoin['high'].iloc[ i + horizon ] / bitcoin['high'].iloc[i]) - 1 )
    i+=1
  
  allreturns.append(returns)

  print (bitcoin['date'].iloc[ i ])


np.shape(allreturns)

2019-12-11 00:00:00
2019-12-11 00:00:00
2019-12-11 00:00:00
2019-12-11 00:00:00
2019-12-11 00:00:00

(5, 406080)

In [ ]:
bitcoin = bitcoin[ bitcoin['date'] < '2019-12-11']
allreturns =  np.array(allreturns)

num_timestamps = len(bitcoin)

index1 = int(num_timestamps * 5/9)
index2 = int (num_timestamps * 6/9)

bitcoin_train = bitcoin[: index1]

bitcoin_val = bitcoin[index1 : index2]

bitcoin_test = bitcoin[index2 : ]


bitcoin_train.loc[: , '1m return'] = allreturns[0 , : index1]
bitcoin_train.loc[: , '1m class'] = np.array(allreturns[0 , : index1] < np.mean(allreturns[0 , : index1])).astype(int)

bitcoin_train.loc[: , '5m return'] = allreturns[1 , : index1]
bitcoin_train.loc[: , '5m class'] = np.array(allreturns[1 , : index1] < np.mean(allreturns[1 , : index1])).astype(int)

bitcoin_train.loc[: , '15m return'] = allreturns[2 , : index1]
bitcoin_train.loc[: , '15m class'] = np.array(allreturns[2 , : index1] < np.mean(allreturns[2 , : index1])).astype(int)

bitcoin_train.loc[: , '60m return'] = allreturns[3 , : index1]
bitcoin_train.loc[: , '60m class'] = np.array(allreturns[3 , : index1] < np.mean(allreturns[3 , : index1])).astype(int)

bitcoin_train.loc[: , '1week return'] = allreturns[4 , : index1]


bitcoin_val.loc[: , '1m return'] = allreturns[0 , index1: index2]
bitcoin_val.loc[: , '1m class'] = np.array(allreturns[0 , index1 :index2 ] < np.mean(allreturns[0 , index1 :index2])).astype(int)

bitcoin_val.loc[: , '5m return'] = allreturns[1 , index1 :index2]
bitcoin_val.loc[: , '5m class'] = np.array(allreturns[1 , index1 :index2] < np.mean(allreturns[1 , index1 :index2])).astype(int)

bitcoin_val.loc[: , '15m return'] = allreturns[2 , index1 :index2]
bitcoin_val.loc[: , '15m class'] = np.array(allreturns[2 , index1 :index2] < np.mean(allreturns[2 ,index1 :index2])).astype(int)

bitcoin_val.loc[: , '60m return'] = allreturns[3 , index1 :index2]
bitcoin_val.loc[: , '60m class'] = np.array(allreturns[3 , index1 :index2] < np.mean(allreturns[3 , index1 :index2])).astype(int)

bitcoin_val.loc[: , '1week return'] = allreturns[4 , index1 :index2]



bitcoin_test.loc[: , '1m return'] = allreturns[0 , index2 :]
bitcoin_test.loc[: , '1m class'] = np.array(allreturns[0 , index2 : ] < np.mean(allreturns[0 , index2 :])).astype(int)

bitcoin_test.loc[: , '5m return'] = allreturns[1 , index2 :]
bitcoin_test.loc[: , '5m class'] = np.array(allreturns[1 , index2 :] < np.mean(allreturns[1 , index2 :])).astype(int)

bitcoin_test.loc[: , '15m return'] = allreturns[2 , index2 :]
bitcoin_test.loc[: , '15m class'] = np.array(allreturns[2 , index2 :] < np.mean(allreturns[2 ,index2 :])).astype(int)

bitcoin_test.loc[: , '60m return'] = allreturns[3 , index2 :]
bitcoin_test.loc[: , '60m class'] = np.array(allreturns[3 , index2 :] < np.mean(allreturns[3 , index2 :])).astype(int)

bitcoin_test.loc[: , '1week return'] = allreturns[4 , index2 :]

bitcoin_train.to_csv('bitcoin_train_raw.csv')  
bitcoin_val.to_csv('bitcoin_val_raw.csv') 
bitcoin_test.to_csv('bitcoin_test_raw.csv')

Loading and splitting the twitter features for training the model:

In [ ]:
import pandas as pd

bitcoin_train = pd.read_csv('/content/drive/MyDrive/Bitcoin_data/bitcoin_train_raw.csv')  
bitcoin_val = pd.read_csv('/content/drive/MyDrive/Bitcoin_data/bitcoin_val_raw.csv') 
bitcoin_test = pd.read_csv('/content/drive/MyDrive/Bitcoin_data/bitcoin_test_raw.csv')

tweets_features_all = pd.read_csv('/content/drive/MyDrive/Bitcoin_data/The features of twitter.csv')
tweets_features_all.drop(tweets_features_all.columns[0],axis=1, inplace=True)


index1 = bitcoin_train.shape[0]
index2 = index1 + bitcoin_val.shape[0]

sentiment_train = tweets_features_all[:index1]
sentiment_val = tweets_features_all[index1 : index2]
sentiment_test = tweets_features_all[index2 :]


sentiment_train.shape[0] == bitcoin_train.shape[0] , sentiment_val.shape[0] == bitcoin_val.shape[0] , sentiment_test.shape[0]== bitcoin_test.shape[0]

(True, True, True)

In [ ]:
bitcoin_train.head()

,Unnamed: 0,date,high,1m return,1m class,5m return,5m class,15m return,15m class,60m return,60m class,1week return
0,0,2019-03-04 00:00:00,3789.70,0.000000,1,0.000881,0,0.003470,0,0.003879,0,0.029081
1,1,2019-03-04 00:01:00,3789.70,0.000251,0,0.002074,0,0.004539,0,0.004143,0,0.029055
2,2,2019-03-04 00:02:00,3790.65,0.000586,0,0.001195,0,0.003559,0,0.003464,0,0.028797
3,3,2019-03-04 00:03:00,3792.87,0.000045,0,0.000609,0,0.003043,0,0.003056,0,0.028329
4,4,2019-03-04 00:04:00,3793.04,0.000000,1,0.000564,0,0.001598,0,0.002681,0,0.028283

In [ ]:
sentiment_train.head()

                        date  num_tweets  sum_score  Weighted_Sentiment_Score
0        2019-03-04 00:00:00           0        0.0                      0.00
1        2019-03-04 00:01:00           0        0.0                      0.00
2        2019-03-04 00:02:00           0        0.0                      0.00
3  2019-03-04 00:03:00+00:00           1        0.2                      0.26
4  2019-03-04 00:04:00+00:00           0        0.0                      0.00

In [ ]:
import warnings
warnings.filterwarnings('ignore')

Following we standardize the bitcoin return features.

In [ ]:
from sklearn.preprocessing import StandardScaler

def standardization( dataframe1, dataframe2, dataframe3 ,startcolumns , step ):

  for i in range (startcolumns , len(dataframe1.columns) ,step):
    
    retrn_data = dataframe1.iloc[:, i].values.reshape(-1, 1)

    scaler = StandardScaler()
    retrn_data_standardized = scaler.fit_transform(retrn_data)

    dataframe1[dataframe1.columns[i]] = retrn_data_standardized.flatten()


##########validation data
    retrn_data = dataframe2.iloc[:, i].values.reshape(-1, 1)

    retrn_data_standardized = scaler.transform(retrn_data)

    dataframe2[dataframe2.columns[i]] = retrn_data_standardized.flatten()

##########test data

    retrn_data = dataframe3.iloc[:, i].values.reshape(-1, 1)

    retrn_data_standardized = scaler.transform(retrn_data)

    dataframe3[dataframe3.columns[i]] = retrn_data_standardized.flatten()




  return dataframe1 , dataframe2, dataframe3

bitcoin_train , bitcoin_val , bitcoin_test = standardization(bitcoin_train , bitcoin_val , bitcoin_test ,3 ,2 )

Following we standardize the tweets' features.

In [ ]:
sentiment_train, sentiment_val , sentiment_test = standardization(sentiment_train, sentiment_val ,sentiment_test, 1, 1)

In [ ]:
import numpy as np
def data_generator_for_model(df , columnnames):

  window_size = 120
  slide_step = 1

  classes = df[columnnames[-1]]

  df = df[columnnames[:-1]]
  
  X = np.array([df[i:i+window_size] for i in range(0, len(df)-window_size+1, slide_step)])[:-1 , : , :]

  Y = np.array([classes[i] for i in range(120,len(classes))])
  
  return X , Y

Following the data is ready to feed to the model for training, validating, and testing :

In [ ]:
dataset_train = pd.concat([sentiment_train ,  bitcoin_train.drop(bitcoin_train.columns[0:2], axis = 1)], axis = 1 )

columns_name = ['num_tweets', 'sum_score', 'Weighted_Sentiment_Score' , '1m return' , '1week return', '1m class']

X_train , Y_train = data_generator_for_model(dataset_train , columns_name)

X_train.shape , Y_train.shape

((225480, 120, 5), (225480,))

In [ ]:
dataset_train.head()

,date,num_tweets,sum_score,Weighted_Sentiment_Score,high,1m return,1m class,5m return,5m class,15m return,15m class,60m return,60m class,1week return
0,2019-03-04 00:00:00,-0.459298,0.028857,0.001857,3789.70,-0.005212,1,0.325736,0,0.744054,0,0.390505,0,-0.235559
1,2019-03-04 00:01:00,-0.459298,0.028857,0.001857,3789.70,0.230412,0,0.781213,0,0.978977,0,0.419614,0,-0.235789
2,2019-03-04 00:02:00,-0.459298,0.028857,0.001857,3790.65,0.545267,0,0.445537,0,0.763580,0,0.344710,0,-0.238037
3,2019-03-04 00:03:00+00:00,1.152675,1.234003,1.177794,3792.87,0.036917,0,0.221749,0,0.650105,0,0.299697,0,-0.242113
4,2019-03-04 00:04:00+00:00,-0.459298,0.028857,0.001857,3793.04,-0.005212,1,0.204622,0,0.332484,0,0.258384,0,-0.242515

In [ ]:
bitcoin_val.reset_index(drop=True, inplace=True)
sentiment_val.reset_index(drop=True, inplace=True)


dataset_val = pd.concat([sentiment_val , bitcoin_val.drop(bitcoin_val.columns[0:2]  , axis = 1)] , axis = 1 )

columns_name = ['num_tweets', 'sum_score', 'Weighted_Sentiment_Score' , '1m return' , '1week return', '1m class']

X_val , Y_val = data_generator_for_model(dataset_val , columns_name)

X_val.shape, Y_val.shape

((45000, 120, 5), (45000,))

In [ ]:
dataset_val.head()

,date,num_tweets,sum_score,Weighted_Sentiment_Score,high,1m return,1m class,5m return,5m class,15m return,15m class,60m return,60m class,1week return
0,2019-08-07 16:00:00+00:00,1.152675,0.028857,0.001857,11653.96,2.416839,0,1.098060,0,0.112374,0,-0.017319,0,-1.341349
1,2019-08-07 16:01:00+00:00,-0.459298,0.028857,0.001857,11683.99,0.639169,0,-0.180466,1,-0.176195,1,-0.254346,1,-1.302518
2,2019-08-07 16:02:00+00:00,2.764648,-1.778861,-0.812253,11692.00,0.334846,0,-0.346600,1,-0.170259,1,-0.357603,1,-1.334528
3,2019-08-07 16:03:00+00:00,-0.459298,0.028857,0.001857,11696.23,-1.327182,1,-0.486549,1,-0.392919,1,-0.575258,1,-1.335675
4,2019-08-07 16:04:00+00:00,-0.459298,0.028857,0.001857,11679.78,0.640206,0,0.351768,0,-0.014769,0,-0.464379,1,-1.314594

In [ ]:
bitcoin_test.reset_index(drop=True, inplace=True)
sentiment_test.reset_index(drop=True, inplace=True)


dataset_test = pd.concat([sentiment_test , bitcoin_test.drop(bitcoin_test.columns[0:2]  , axis = 1)] , axis = 1 )

columns_name = ['num_tweets', 'sum_score', 'Weighted_Sentiment_Score' , '1m return' , '1week return', '1m class']

X_test , Y_test = data_generator_for_model(dataset_test , columns_name)

X_test.shape, Y_test.shape

((135240, 120, 5), (135240,))

In [ ]:
dataset_test.head()

,date,num_tweets,sum_score,Weighted_Sentiment_Score,high,1m return,1m class,5m return,5m class,15m return,15m class,60m return,60m class,1week return
0,2019-09-08 00:00:00+00:00,1.152675,-4.791726,-5.787369,10505.07,0.792907,0,0.299616,0,0.448128,0,0.035909,0,-0.607273
1,2019-09-08 00:01:00+00:00,-0.459298,0.028857,0.001857,10513.99,0.532078,0,-0.026815,1,0.270434,0,0.149370,0,-0.614617
2,2019-09-08 00:02:00+00:00,-0.459298,0.028857,0.001857,10520.00,0.194928,0,-0.245338,1,0.145938,0,0.187327,0,-0.619524
3,2019-09-08 00:03:00+00:00,-0.459298,0.028857,0.001857,10522.24,-0.974433,1,-0.190848,1,-0.204028,1,-0.039797,0,-0.620034
4,2019-09-08 00:04:00+00:00,-0.459298,0.028857,0.001857,10511.39,0.193304,0,0.189711,0,0.232862,0,0.235995,0,-0.617856

following we save the variables of X and Y for train, val, and test as a pickle object so later they can be loaded for training the model

In [ ]:
import pickle 

filepath = '/content/drive/MyDrive/Dataset_with_memory /1min/'

with open(filepath+'X_train.pickle', 'wb') as file:
    # Serialize the object and write to file
    pickle.dump(X_train, file)
  
with open(filepath+'Y_train.pickle', 'wb') as file:
    # Serialize the object and write to file
    pickle.dump(Y_train, file)
  
with open(filepath+'X_val.pickle', 'wb') as file:
    # Serialize the object and write to file
    pickle.dump(X_val, file)
  
with open(filepath+'Y_val.pickle', 'wb') as file:
    # Serialize the object and write to file
    pickle.dump(Y_val, file)
  
with open(filepath+'X_test.pickle', 'wb') as file:
    # Serialize the object and write to file
    pickle.dump(X_test, file)
  
with open(filepath+'Y_test.pickle', 'wb') as file:
    # Serialize the object and write to file
    pickle.dump(Y_test, file)

So far, the data regarding 1 minute retursn were processed and saved to file. In the following the data ragarding other time horizons will be generated for models.

In [ ]:
import pickle

columns_name_5 = ['num_tweets', 'sum_score', 'Weighted_Sentiment_Score' , '5m return' , '1week return', '5m class']
columns_name_15 = ['num_tweets', 'sum_score', 'Weighted_Sentiment_Score' , '15m return' , '1week return', '15m class']
columns_name_60 = ['num_tweets', 'sum_score', 'Weighted_Sentiment_Score' , '60m return' , '1week return', '60m class']

def save_pickle (x, filename):

  with open(filename, 'wb') as file:
    pickle.dump(x, file)


data_dict = {'train' : dataset_train , 'val' : dataset_val , 'test' : dataset_test}


def genet_save(namecolumns , stringreturn , filepath):

  for key in data_dict:
    
    X , Y = data_generator_for_model(data_dict[key], namecolumns)
    print(Y)
    save_pickle(X , filepath+'X' + '_' + key + '_' + stringreturn + '.pickle')
    save_pickle(Y , filepath+'Y' + '_' + key + '_' + stringreturn + '.pickle')

genet_save(columns_name_5 , '5min', '/content/drive/MyDrive/Dataset_with_memory /5min/')
genet_save(columns_name_15 , '15min', '/content/drive/MyDrive/Dataset_with_memory /15min/')
genet_save(columns_name_60 , '60min', '/content/drive/MyDrive/Dataset_with_memory /60min/')

[1 1 0 ... 0 0 0]
[0 0 1 ... 0 0 0]
[0 0 0 ... 1 0 0]
[1 1 1 ... 0 0 0]
[1 1 1 ... 0 0 0]
[0 0 1 ... 0 0 0]
[1 1 1 ... 1 1 1]
[1 1 1 ... 0 0 0]
[1 1 1 ... 0 0 0]